services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: npm-registry
    restart: unless-stopped

    ports:
      - "6010:4873"

    volumes:
      - ./config:/verdaccio/conf
      - ./storage:/verdaccio/storage

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"