storage: /verdaccio/storage

web:
  title: Local NPM Registry

uplinks:
  chabokan:
    url: https://mirror2.chabokan.net/npm/
    timeout: 120s

  npmjs:
    url: https://registry.npmjs.org/
    timeout: 120s

packages:
  "@*/*":
    access: $all
    proxy: chabokan npmjs

  "*":
    access: $all
    proxy: chabokan npmjs

log:
  - { type: stdout, format: pretty, level: http }

